service: serverless-graphql

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

functions:
  graphql:
    handler: lambda.handler
    events:
      - http:
          path: graphql
          method: post
          cors: true
  playground:
    handler: lambda.handler
    events:
      - http:
          path: graphiql
          method: get